# Generated by Django 5.2.7 on 2025-10-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inscricao_estadual", models.CharField(max_length=200, unique=True)),
                ("cnpj", models.CharField(max_length=14, unique=True)),
                ("razao_social", models.CharField(max_length=200)),
                ("codigo_apelido", models.CharField(max_length=200, unique=True)),
                ("chave_api_dominio", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Cliente para Consulta",
                "verbose_name_plural": "Clientes para Consulta",
            },
        ),
    ]
